In [1]:
import tensorflow as tf
print(tf.__version__)

2.11.0


In [2]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
? tf.constant

Signature:  tf.constant(value, dtype=None, shape=None, name='Const')
Docstring:
Creates a constant tensor from a tensor-like object.

Note: All eager `tf.Tensor` values are immutable (in contrast to
`tf.Variable`). There is nothing especially _constant_ about the value
returned from `tf.constant`. This function is not fundamentally different from
`tf.convert_to_tensor`. The name `tf.constant` comes from the `value` being
embedded in a `Const` node in the `tf.Graph`. `tf.constant` is useful
for asserting that the value can be embedded that way.

If the argument `dtype` is not specified, then the type is inferred from
the type of `value`.

>>> # Constant 1-D Tensor from a python list.
>>> tf.constant([1, 2, 3, 4, 5, 6])
<tf.Tensor: shape=(6,), dtype=int32,
    numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>
>>> # Or a numpy array
>>> a = np.array([[1, 2, 3], [4, 5, 6]])
>>> tf.constant(a)
<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
  array([[1, 2, 3],
         [4, 5, 6]])>

If `dtype` is

In [4]:
scalar.ndim

0

In [5]:
vector = tf.constant([10,10])

In [6]:
vector.ndim

1

In [11]:
matrix =tf.constant([[10,7],[8,10]])

In [12]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 8, 10]], dtype=int32)>

In [13]:
matrix.ndim

2

In [15]:
matrix_two = tf.constant([[10.,7.],[3.,2.],[8.,9.]],dtype=tf.float16)

In [16]:
matrix_two

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [17]:
matrix_two.ndim

2

In [18]:
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])

In [19]:
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [20]:
tensor.ndim

3

In [21]:
changable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])

In [23]:
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [24]:
changable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [27]:
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [30]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

random_1, random_2, random_1==random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [38]:
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [34]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [39]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [41]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [42]:
tf.zeros(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [50]:
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
tf_A = tf.constant(numpy_A,shape=[4,2,3])

In [51]:
tf_A

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]], dtype=int32)>

In [52]:
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [53]:
tf_A.ndim

3

In [2]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [4]:
 rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [5]:
rank_4_tensor.dtype

tf.float32

In [6]:
rank_4_tensor.shape[0]

2

In [7]:
rank_4_tensor.shape[-1]

5

In [8]:
tf.size(rank_4_tensor).numpy()

120

In [9]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [10]:
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [12]:
rank_2_tensor = tf.constant([[10,7],[3,4]])

In [14]:
rank_2_tensor.shape

TensorShape([2, 2])

In [16]:
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [17]:
rank_3_tensor = rank_2_tensor[...,tf.newaxis]

In [18]:
rank_3_tensor.shape

TensorShape([2, 2, 1])

In [21]:
tf.expand_dims(rank_2_tensor, axis=2)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [22]:
tensor = tf.constant([[10,7],[3,4]])

In [23]:
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [24]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [25]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [27]:
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [28]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [29]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [30]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [31]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [32]:
# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [33]:
X.shape

TensorShape([3, 2])

In [34]:
Y.shape

TensorShape([3, 2])

In [35]:
X @ Y

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]

In [36]:
tf.reshape(Y, shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [37]:
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [40]:
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [41]:
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [42]:
tf.matmul(tf.reshape(X,(2,3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [45]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [46]:
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [47]:
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [48]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [49]:
tf.matmul(X, tf.reshape(Y, (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [50]:
B = tf.constant([1.7,7.4])

In [51]:
B.dtype

tf.float32

In [52]:
C = tf.constant([7,10])

In [53]:
C.dtype

tf.int32

In [54]:
B = tf.cast(B, dtype=tf.float16)

In [55]:
B.dtype

tf.float16

In [56]:
C = tf.cast(C, dtype=tf.float32)

In [57]:
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [58]:
D = tf.constant([-7,-10])

In [59]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [64]:
E = tf.constant(np.random.randint(low=0, high=100, size=50))

In [63]:
import numpy as np

In [66]:
tf.reduce_min(E).numpy()

3

In [68]:
tf.reduce_max(E).numpy()

98

In [70]:
tf.reduce_mean(E).numpy()

47

In [71]:
tf.reduce_sum(E).numpy()

2353

In [76]:
E = tf.cast(E, dtype=tf.float32)

In [77]:
tf.math.reduce_std(E)

<tf.Tensor: shape=(), dtype=float32, numpy=28.181847>

In [80]:
import tensorflow_probability as tfp

In [81]:
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=float32, numpy=794.21643>

In [82]:
F = tf.constant(np.random.random(50))

In [83]:
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.83989472, 0.17257818, 0.30393324, 0.52486455, 0.43449279,
       0.25669544, 0.71727829, 0.62908769, 0.48225532, 0.73583699,
       0.29851529, 0.71590164, 0.90715512, 0.36671224, 0.82473126,
       0.65762829, 0.59214045, 0.64436867, 0.39284644, 0.22982484,
       0.81467682, 0.49210853, 0.54604683, 0.74185485, 0.93068127,
       0.91330847, 0.37923313, 0.35533678, 0.63036405, 0.33442251,
       0.38967032, 0.6528902 , 0.53639037, 0.13499258, 0.8225639 ,
       0.29445133, 0.28369444, 0.51126993, 0.06793033, 0.20728892,
       0.17120012, 0.18799666, 0.05597152, 0.69721771, 0.32282545,
       0.09337073, 0.51201905, 0.94787389, 0.70385374, 0.41896079])>

In [84]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [85]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [87]:
F[tf.argmax(F)].numpy()

0.9478738870623674

In [88]:
G = tf.constant(np.random.randint(0,100,50), shape=(1,1,1,1,50))

In [89]:
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=int64, numpy=
array([[[[[92, 35, 60, 39, 36, 54, 96, 39, 23,  9, 49, 59, 84,  1, 57,
           91, 59, 98, 13, 40,  9, 32, 46, 14,  3, 16, 93, 43, 94, 54,
           57, 41, 22, 66, 47, 85, 90, 29, 23, 33, 20, 62, 46, 60,  2,
           97, 15, 65, 41, 30]]]]])>

In [90]:
G_squeezed = tf.squeeze(G)

In [91]:
G_squeezed


<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([92, 35, 60, 39, 36, 54, 96, 39, 23,  9, 49, 59, 84,  1, 57, 91, 59,
       98, 13, 40,  9, 32, 46, 14,  3, 16, 93, 43, 94, 54, 57, 41, 22, 66,
       47, 85, 90, 29, 23, 33, 20, 62, 46, 60,  2, 97, 15, 65, 41, 30])>

In [92]:
some_list = [1,2,3,4]

In [96]:
tf.one_hot(some_list, depth=6, on_value='We are live', off_value='offfff')

<tf.Tensor: shape=(4, 6), dtype=string, numpy=
array([[b'offfff', b'We are live', b'offfff', b'offfff', b'offfff',
        b'offfff'],
       [b'offfff', b'offfff', b'We are live', b'offfff', b'offfff',
        b'offfff'],
       [b'offfff', b'offfff', b'offfff', b'We are live', b'offfff',
        b'offfff'],
       [b'offfff', b'offfff', b'offfff', b'offfff', b'We are live',
        b'offfff']], dtype=object)>

In [97]:
H= tf.constant(np.arange(1,10))

In [98]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [99]:
H = tf.cast(H,dtype=tf.float32)

In [100]:
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [101]:
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [102]:
I = tf.Variable(np.arange(0,5))